# fly.toml app configuration file generated for synced-editor on 2023-08-14T23:03:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "synced-editor"
primary_region = "sin"

[build]

[env]
  PORT = "8080"
  FRONTEND_ORIGIN = "https://realtime-notetaking.netlify.app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
